name: context
on: workflow_dispatch

jobs:
  contenxt:
    runs-on: ubuntu-latest
    steps:
      - name: github context
        run: echo '${{ toJSON(github) }}'
      - name: check gitbub context
        run: |
          echo ${{ github.repository }}
          echo ${{ github.event_name }}
